<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'IaxsCore\Controller\Plugin\InstanceIterator'                => __DIR__ . '/src/IaxsCore/Controller/Plugin/InstanceIterator.php',
    'IaxsCore\Controller\Event\IteratorEvent'                    => __DIR__ . '/src/IaxsCore/Controller/Event/IteratorEvent.php',
    'IaxsCore\Entity\InstanceInterface'                          => __DIR__ . '/src/IaxsCore/Entity/InstanceInterface.php',
    'IaxsCore\Entity\InstanceIterator\ArrayInstanceIterator'     => __DIR__ . '/src/IaxsCore/Entity/InstanceIterator/ArrayInstanceIterator.php',
    'IaxsCore\Entity\InstanceIterator\InstanceIteratorInterface' => __DIR__ . '/src/IaxsCore/Entity/InstanceIterator/InstanceIteratorInterface.php',
    'IaxsCore\Service\InstanceAwareInterface'                    => __DIR__ . '/src/IaxsCore/Service/InstanceAwareInterface.php',
    'IaxsCore\Service\ServiceManager'                            => __DIR__ . '/src/IaxsCore/Service/ServiceManager.php',
    'IaxsCore\Exception\InvalidArgumentException'                => __DIR__ . '/src/IaxsCore/Exception/InvalidArgumentException.php',
    'IaxsCore\Exception\NullPointerException'                    => __DIR__ . '/src/IaxsCore/Exception/NullPointerException.php',
);